import re
import uuid
from pathlib import Path
from typing import Any

import pandas as pd

from app.datasets.loader import DatasetLoader
from app.powerbi.dashboard_planner import DashboardPlanner
from app.powerbi.semantic import SemanticAnalyzer


class SemanticModelBuildError(Exception):
    pass


class SemanticModelBuilder:
    def __init__(self) -> None:
        self.loader = DatasetLoader()
        self.semantic_analyzer = SemanticAnalyzer()
        self.dashboard_planner = DashboardPlanner()

    def build(
        self,
        dataset_id: str,
        model_directory: Path,
        data_path: Path,
    ) -> dict[str, Any]:

        df = self.loader.load(dataset_id)

        semantic = self.semantic_analyzer.analyze(
            dataset_id
        )

        dashboard_plan = (
            self.dashboard_planner.create_plan(
                dataset_id
            )
        )

        distributions = [
            visual
            for visual in dashboard_plan.get(
                "visuals",
                [],
            )
            if (
                visual.get("type")
                == "distribution_chart"
            )
        ]

        definition_directory = (
            model_directory / "definition"
        )

        tables_directory = (
            definition_directory / "tables"
        )

        tables_directory.mkdir(
            parents=True,
            exist_ok=True,
        )

        # Remove template/sample tables.
        for file in tables_directory.glob(
            "*.tmdl"
        ):
            file.unlink()

        # Remove relationships generated by the
        # template's automatic date table.
        relationships_path = (
            definition_directory
            / "relationships.tmdl"
        )

        if relationships_path.exists():
            relationships_path.unlink()

        self._write_model_tmdl(
            definition_directory
        )

        table_path = (
            tables_directory / "Dataset.tmdl"
        )

        table_content = self._build_table(
            df=df,
            semantic=semantic,
            data_path=data_path,
            distributions=distributions,
        )

        table_path.write_text(
            table_content,
            encoding="utf-8",
        )

        return {
            "dataset_id": dataset_id,
            "table": "Dataset",
            "column_count": len(df.columns),
            "distribution_columns": [
                {
                    "field": distribution["field"],
                    "bin_column": (
                        f"{distribution['field']} Bin"
                    ),
                    "sort_column": (
                        f"{distribution['field']} "
                        "Bin Order"
                    ),
                }
                for distribution in distributions
                if distribution.get("field")
            ],
            "table_definition": str(
                table_path
            ),
            "data_source": str(
                data_path
            ),
        }

    @staticmethod
    def _write_model_tmdl(
        definition_directory: Path,
    ) -> None:

        content = """model Model
\tculture: en-US
\tdefaultPowerBIDataSourceVersion: powerBI_V3
\tsourceQueryCulture: en-US
\tvalueFilterBehavior: independent
\tdataAccessOptions
\t\tlegacyRedirects
\t\treturnErrorValuesAsNull

annotation __PBI_TimeIntelligenceEnabled = 0

annotation PBI_ProTooling = ["DevMode"]

ref cultureInfo en-US
"""

        path = (
            definition_directory
            / "model.tmdl"
        )

        path.write_text(
            content,
            encoding="utf-8",
        )

    def _build_table(
        self,
        df: pd.DataFrame,
        semantic: dict[str, Any],
        data_path: Path,
        distributions: list[dict[str, Any]],
    ) -> str:

        semantic_columns = {
            column["name"]: column
            for column in semantic["columns"]
        }

        lines = [
            "table Dataset",
            f"\tlineageTag: {uuid.uuid4()}",
            "",
        ]

        # --------------------------------------------------
        # Original dataset columns
        # --------------------------------------------------

        for column in df.columns:
            name = str(column)

            info = semantic_columns.get(
                name,
                {},
            )

            lines.extend(
                self._build_column(
                    name=name,
                    series=df[column],
                    semantic_role=info.get(
                        "semantic_role"
                    ),
                )
            )

        # --------------------------------------------------
        # Generated distribution columns
        #
        # Example:
        #
        # Salary Bin
        # Salary Bin Order
        # --------------------------------------------------

        generated_fields: set[str] = set()

        for distribution in distributions:
            field = distribution.get(
                "field"
            )

            if not field:
                continue

            if field not in df.columns:
                raise SemanticModelBuildError(
                    "Distribution field does not "
                    f"exist: {field}"
                )

            # Avoid generating the same distribution
            # columns more than once.
            if field in generated_fields:
                continue

            generated_fields.add(field)

            bin_name = (
                f"{field} Bin"
            )

            bin_order_name = (
                f"{field} Bin Order"
            )

            lines.extend(
                self._build_bin_column(
                    name=bin_name,
                    sort_column=bin_order_name,
                )
            )

            lines.extend(
                self._build_bin_order_column(
                    name=bin_order_name,
                )
            )

        # --------------------------------------------------
        # Partition
        # --------------------------------------------------

        lines.extend(
            self._build_partition(
                df=df,
                semantic=semantic,
                data_path=data_path,
                distributions=distributions,
            )
        )

        lines.extend(
            [
                "",
                "\tannotation PBI_ResultType = Table",
            ]
        )

        return "\n".join(lines) + "\n"

    def _build_column(
        self,
        name: str,
        series: pd.Series,
        semantic_role: str | None,
    ) -> list[str]:

        tmdl_name = self._tmdl_identifier(
            name
        )

        data_type = self._tmdl_data_type(
            series,
            semantic_role,
        )

        summarize_by = (
            self._summarization(
                semantic_role
            )
        )

        lines = [
            f"\tcolumn {tmdl_name}",
            f"\t\tdataType: {data_type}",
        ]

        if data_type == "int64":
            lines.append(
                "\t\tformatString: 0"
            )

        elif data_type == "dateTime":
            lines.append(
                "\t\tformatString: Long Date"
            )

        lines.extend(
            [
                (
                    "\t\tlineageTag: "
                    f"{uuid.uuid4()}"
                ),
                (
                    "\t\tsummarizeBy: "
                    f"{summarize_by}"
                ),
                (
                    "\t\tsourceColumn: "
                    f"{self._source_column(name)}"
                ),
                "",
                (
                    "\t\tannotation "
                    "SummarizationSetBy = Automatic"
                ),
            ]
        )

        if semantic_role == "currency":
            lines.extend(
                [
                    "",
                    (
                        "\t\tannotation "
                        "PBI_FormatHint = "
                        '{"isGeneralNumber":true}'
                    ),
                ]
            )

        lines.append("")

        return lines

    def _build_bin_column(
        self,
        name: str,
        sort_column: str,
    ) -> list[str]:

        tmdl_name = self._tmdl_identifier(
            name
        )

        sort_name = self._tmdl_identifier(
            sort_column
        )

        return [
            f"\tcolumn {tmdl_name}",
            "\t\tdataType: string",
            (
                "\t\tlineageTag: "
                f"{uuid.uuid4()}"
            ),
            "\t\tsummarizeBy: none",
            (
                "\t\tsourceColumn: "
                f"{self._source_column(name)}"
            ),
            (
                "\t\tsortByColumn: "
                f"{sort_name}"
            ),
            "",
            (
                "\t\tannotation "
                "SummarizationSetBy = Automatic"
            ),
            "",
        ]

    def _build_bin_order_column(
        self,
        name: str,
    ) -> list[str]:

        tmdl_name = self._tmdl_identifier(
            name
        )

        return [
            f"\tcolumn {tmdl_name}",
            "\t\tdataType: double",
            (
                "\t\tlineageTag: "
                f"{uuid.uuid4()}"
            ),
            "\t\tsummarizeBy: none",
            (
                "\t\tsourceColumn: "
                f"{self._source_column(name)}"
            ),
            "",
            (
                "\t\tannotation "
                "SummarizationSetBy = Automatic"
            ),
            "",
        ]

    def _build_partition(
        self,
        df: pd.DataFrame,
        semantic: dict[str, Any],
        data_path: Path,
        distributions: list[dict[str, Any]],
    ) -> list[str]:

        windows_path = str(
            data_path.resolve()
        ).replace(
            '"',
            '""',
        )

        column_count = len(
            df.columns
        )

        semantic_columns = {
            column["name"]: column
            for column in semantic["columns"]
        }

        transformations = []

        for column in df.columns:
            name = str(column)

            info = semantic_columns.get(
                name,
                {},
            )

            semantic_role = info.get(
                "semantic_role"
            )

            m_type = self._power_query_type(
                series=df[column],
                semantic_role=semantic_role,
            )

            escaped_name = name.replace(
                '"',
                '""',
            )

            transformations.append(
                f'{{"{escaped_name}", {m_type}}}'
            )

        transformations_text = ", ".join(
            transformations
        )

        lines = [
            "\tpartition Dataset = m",
            "\t\tmode: import",
            "\t\tsource =",
            "\t\t\t\tlet",
            (
                "\t\t\t\t\t"
                "Source = Csv.Document("
                f'File.Contents("{windows_path}"),'
                "[Delimiter=\",\", "
                f"Columns={column_count}, "
                "Encoding=65001, "
                "QuoteStyle=QuoteStyle.Csv]),"
            ),
            (
                "\t\t\t\t\t"
                '#"Promoted Headers" = '
                "Table.PromoteHeaders("
                "Source, "
                "[PromoteAllScalars=true]),"
            ),
            (
                "\t\t\t\t\t"
                '#"Changed Type" = '
                "Table.TransformColumnTypes("
                '#"Promoted Headers",'
                f"{{{transformations_text}}})"
            ),
        ]

        previous_step = (
            '#"Changed Type"'
        )

        distribution_steps = []

        generated_fields: set[str] = set()

        for index, distribution in enumerate(
            distributions,
            start=1,
        ):
            field = distribution.get(
                "field"
            )

            if not field:
                continue

            if field not in df.columns:
                raise SemanticModelBuildError(
                    "Distribution field does not "
                    f"exist: {field}"
                )

            # Avoid generating duplicate M columns
            # if the planner somehow contains the
            # same distribution field more than once.
            if field in generated_fields:
                continue

            generated_fields.add(field)

            try:
                bin_count = int(
                    distribution.get(
                        "bin_count",
                        10,
                    )
                )

            except (
                TypeError,
                ValueError,
            ) as exc:
                raise SemanticModelBuildError(
                    "Distribution bin_count "
                    "must be an integer."
                ) from exc

            if bin_count <= 0:
                raise SemanticModelBuildError(
                    "Distribution bin_count must "
                    "be greater than zero."
                )

            numeric = pd.to_numeric(
                df[field],
                errors="coerce",
            ).dropna()

            if numeric.empty:
                continue

            minimum = float(
                numeric.min()
            )

            maximum = float(
                numeric.max()
            )

            if minimum == maximum:
                bin_width = 1.0

            else:
                bin_width = (
                    maximum - minimum
                ) / bin_count

            # --------------------------------------------------
            # Generated column names
            # --------------------------------------------------

            bin_name = (
                f"{field} Bin"
            )

            bin_order_name = (
                f"{field} Bin Order"
            )

            escaped_field = (
                self._power_query_field_name(
                    field
                )
            )

            escaped_bin_name = (
                bin_name.replace(
                    '"',
                    '""',
                )
            )

            escaped_bin_order_name = (
                bin_order_name.replace(
                    '"',
                    '""',
                )
            )

            # --------------------------------------------------
            # Numeric constants for Power Query M
            # --------------------------------------------------

            minimum_m = self._m_number(
                minimum
            )

            maximum_m = self._m_number(
                maximum
            )

            bin_width_m = self._m_number(
                bin_width
            )

            # --------------------------------------------------
            # BinStart expression
            #
            # Maximum value is placed into the final
            # existing bin rather than creating an
            # additional bin.
            # --------------------------------------------------

            if minimum == maximum:
                bin_start_expression = (
                    minimum_m
                )

            else:
                bin_start_expression = (
                    "if "
                    f"{escaped_field} = "
                    f"{maximum_m} "
                    "then "
                    f"{maximum_m} - "
                    f"{bin_width_m} "
                    "else "
                    f"{minimum_m} + "
                    "Number.RoundDown(("
                    f"{escaped_field} - "
                    f"{minimum_m}"
                    ") / "
                    f"{bin_width_m}"
                    ") * "
                    f"{bin_width_m}"
                )

            # --------------------------------------------------
            # Step 1:
            # Numeric bin-order column
            #
            # Salary Bin Order:
            # 0
            # 9000
            # 18000
            # ...
            # --------------------------------------------------

            order_step_name = (
                '#"Added Distribution '
                f'Bin Order {index}"'
            )

            order_expression = (
                f"{order_step_name} = "
                "Table.AddColumn("
                f"{previous_step}, "
                f'"{escaped_bin_order_name}", '
                "each "
                f"if {escaped_field} = null "
                "then null "
                "else "
                f"{bin_start_expression}, "
                "type number)"
            )

            distribution_steps.append(
                order_expression
            )

            # --------------------------------------------------
            # Step 2:
            # Human-readable bin label
            #
            # Salary Bin:
            # 0 - 9000
            # 9000 - 18000
            # ...
            # --------------------------------------------------

            bin_step_name = (
                '#"Added Distribution '
                f'Bin {index}"'
            )

            bin_order_reference = (
                self._power_query_field_name(
                    bin_order_name
                )
            )

            bin_expression = (
                f"{bin_step_name} = "
                "Table.AddColumn("
                f"{order_step_name}, "
                f'"{escaped_bin_name}", '
                "each "
                f"if {bin_order_reference} = null "
                "then null "
                "else "
                "let "
                "BinStart = "
                f"{bin_order_reference}, "
                "BinEnd = BinStart + "
                f"{bin_width_m} "
                "in "
                "Number.ToText(BinStart) "
                '& " - " & '
                "Number.ToText(BinEnd), "
                "type text)"
            )

            distribution_steps.append(
                bin_expression
            )

            previous_step = (
                bin_step_name
            )

        # --------------------------------------------------
        # Add commas between generated Power Query steps.
        # --------------------------------------------------

        if distribution_steps:
            lines[-1] += ","

            for step_index, step in enumerate(
                distribution_steps
            ):
                is_last = (
                    step_index
                    == len(distribution_steps) - 1
                )

                suffix = (
                    ""
                    if is_last
                    else ","
                )

                lines.append(
                    "\t\t\t\t\t"
                    f"{step}{suffix}"
                )

        lines.extend(
            [
                "\t\t\t\tin",
                (
                    "\t\t\t\t\t"
                    f"{previous_step}"
                ),
            ]
        )

        return lines

    @staticmethod
    def _tmdl_data_type(
        series: pd.Series,
        semantic_role: str | None,
    ) -> str:

        if semantic_role == "datetime":
            return "dateTime"

        if pd.api.types.is_integer_dtype(
            series
        ):
            return "int64"

        if pd.api.types.is_numeric_dtype(
            series
        ):
            return "double"

        if pd.api.types.is_bool_dtype(
            series
        ):
            return "boolean"

        return "string"

    @staticmethod
    def _power_query_type(
        series: pd.Series,
        semantic_role: str | None,
    ) -> str:

        if semantic_role == "datetime":
            return "type datetime"

        if pd.api.types.is_bool_dtype(
            series
        ):
            return "type logical"

        if pd.api.types.is_integer_dtype(
            series
        ):
            return "Int64.Type"

        if pd.api.types.is_numeric_dtype(
            series
        ):
            return "type number"

        return "type text"

    @staticmethod
    def _summarization(
        semantic_role: str | None,
    ) -> str:

        if semantic_role in {
            "currency",
            "measure",
        }:
            return "sum"

        return "none"

    @staticmethod
    def _tmdl_identifier(
        name: str,
    ) -> str:

        if re.fullmatch(
            r"[A-Za-z_][A-Za-z0-9_]*",
            name,
        ):
            return name

        escaped = name.replace(
            "'",
            "''",
        )

        return f"'{escaped}'"

    @staticmethod
    def _source_column(
        name: str,
    ) -> str:

        if (
            name.strip() == name
            and '"' not in name
        ):
            return name

        escaped = name.replace(
            '"',
            '""',
        )

        return f'"{escaped}"'

    @staticmethod
    def _power_query_field_name(
        name: str,
    ) -> str:

        if re.fullmatch(
            r"[A-Za-z_][A-Za-z0-9_]*",
            name,
        ):
            return f"[{name}]"

        escaped = name.replace(
            '"',
            '""',
        )

        return f'[#"{escaped}"]'

    @staticmethod
    def _m_number(
        value: float,
    ) -> str:

        if float(value).is_integer():
            return str(
                int(value)
            )

        return format(
            value,
            ".15g",
        )